---
js:
  m:
    - jquery.tip
    - jquery.validator
    - jquery.simpleList
    - jquery.dialog
    - jquery.inlineEdit
    - jquery.message
    - genericResponseHandler
    - jquery.caret
    - jquery.numeric
    - jquery.editTo
    - jquery.resetForm
    - jquery.pagedList
    - mogade
  stats:
    - stats/excanvas
    - stats/jquery.dateRange
    - stats/jquery.flot
    - stats/statistics
  s:
    - scores
  u:
    - fileuploader

css:
  main:
    - reset
    - mogade
  m:
    - manage
    - dialog
  h:
    - home
  stats:
    - statistics