---
js:
  manage:
    - jquery.tip
    - jquery.validator
    - jquery.simpleList
    - jquery.dialog
    - jquery.inlineEdit
    - jquery.message
    - genericResponseHandler
    - jquery.caret
    - jquery.numeric
    - jquery.editTo
    - jquery.resetForm
    - mogade

css:
  main:
    - reset
    - mogade
  manage:
    - manage
    - dialog