---
js:
  h:
    - head
  m:
    - manage/jquery.tip
    - manage/jquery.validator
    - manage/jquery.simpleList
    - manage/jquery.dialog
    - manage/jquery.inlineEdit
    - manage/jquery.message
    - manage/genericResponseHandler
    - manage/jquery.caret
    - manage/jquery.numeric
    - manage/jquery.editTo
    - manage/jquery.resetForm
    - manage/jquery.pagedList
    - manage/manage
  stats:
    - stats/excanvas
    - stats/jquery.dateRange
    - stats/jquery.flot
    - stats/statistics
  s:
    - scores
  pi:
    - profile_images/fileuploader
    - profile_images/images
  fb:
    - facebook/jquery.colorbox

css:
  main:
    - reset
    - mogade
  fb:
    - reset
    - facebook
    - colorbox
    - purdySelect
  m:
    - manage
    - dialog
  h:
    - home
  stats:
    - statistics