---
js:
  manage:
    - jquery.tip
    - jquery.validator
    - jquery.simpleList
    - jquery.dialog
    - jquery.inlineEdit
    - jquery.message
    - genericResponseHandler
    - jquery.caret
    - jquery.numeric
    - jquery.editTo
    - jquery.resetForm
    - mogade
  stats:
    - excanvas
    - jquery.dateRange
    - jquery.flot
    - statistics
  scores:
    - scores

css:
  main:
    - reset
    - mogade
  manage:
    - manage
    - dialog
  stats:
    - statistics