---
- :name: Pirate's Mind
  :image: piratesmind.png
  :description: Pirate's Mind is a addicting game of memory with a twist. Uncover as many matching coins as you can before the timer runs out. The more coins you match at a time the greater your score. Increase the Combo Meter to maximize your scoring potential!
  :developer: 
    :name: M80 Games
    :link: http://www.m80games.com/
  :platform: 
    :name: Windows Phone
    :link: http://social.zune.net/redirect?type=phoneApp&id=ebc13c5d-9b23-e011-854c-00237de2db9e
- :name: Breakout
  :image: breakout.png
  :description: Breakout is a modern approach to the classic brick breaking game, featuring 80 levels, an integrated level editor, multiple weapons, an array of power-ups, online scoreboards, in-game achievements, multiple game modes, and much more.
  :developer: 
    :name: Clayton Industries
    :link: http://www.appsfuze.com/publisher/clayton-industries
  :platform: 
    :name: Windows Phone
    :link: http://redirect.zune.net/External/LaunchZuneProtocol.aspx?pathuri=navigate?phoneAppID=04db085e-d301-4cb9-8f0e-92d78229766e
- :name: Ace of Dynamites
  :image: aceofdynamites.png
  :description: The gems from the kingdom of the Round Happy Faces people have been stolen by their enemies. They're now scattered in the lands of the Death's Heads tribe, and guarded 24/7. You've been chosen to go to hostile territory and get as many gems back as possible. 
  :developer: 
    :name: Fairy Engine LLC
    :link: http://www.fairyengine.com/
  :platform: 
    :name: Windows Phone
    :link: http://social.zune.net/redirect?type=phoneApp&id=9d694358-3bab-e011-a53c-78e7d1fa76f8
- :name: boxStraik
  :image: boxStraik.png
  :description: boxStraik is fun, fast-paced WP7 exclusive. boxStraik is all about boxes, you play as a box, and you try to avoid other boxes. Worried about visuals? Four totally different and unique visual themes guarantees you hours of joy! Battle your way to local and global top 10!
  :developer: 
    :name: Ignoring Games
    :link: http://twitter.com/#!/IgnoringGames
  :platform: 
    :name: Windows Phone
    :link: http://www.microsoft.com/windowsphone//s?appid=fa501528-a1cb-4035-98c0-67d39e511ece
- :name: Assault Heli
  :image: assaultheli.png
  :description: Take flight in one of the world's most advanced pieces of weaponry against a rogue enemy. What seemed like over night, a secret society emerged and surprised the world by taking command of most of its armed forces. The risks are high and chances are slim, but it's up to you to slow their advances to buy time for defense forces to organize.
  :developer: 
    :name: Pettit Gaming
    :link: http://www.pettitgaming.com/
  :platform: 
    :name: Windows Phone
    :link: http://windowsphone.com/s?appid=9e87c9ef-15a9-e011-a53c-78e7d1fa76f8
- :name: Monkey Mini Golf
  :image: monkeyminigolf.png
  :description: Put your ingenious mind to the test with mini golf madness! Putt the ball through tropical island mayhem, with a range of unique and interesting beach is land course designs. Use your cunning to figure out intricate routes and collect all the bananas scattered throughout the courses.
  :developer: 
    :name: Ignition Studios
    :link: http://www.ignitionstudios.com.au/
  :platform: 
    :name: Windows Phone
    :link: http://windowsphone.com/s?appid=454a0ed3-eae4-427b-b0b4-121c66c04b1a
- :name: Wonder Witches
  :image: wonderwitches.png
  :description: Take control and guide the Wonder Witches through their dangerous world. Unlock new witches as you progress through the game. Each witch has a broomstick with magical powers.
  :developer: 
    :name: Johann Digital Works
    :link: https://twitter.com/#!/johanndigiworks
  :platform: 
    :name: Windows Phone
    :link: http://redirect.zune.net/External/LaunchZuneProtocol.aspx?pathuri=navigate?phoneAppID=754c1f1c-2fe1-4efe-914b-2af4cd7db010
- :name: Bubble Burst
  :image: bubbleburst.png
  :description: The return of a Windows Phone classic! Earn points by bursting groups of 2 or more bubbles of the same color that are next to each other. The more bubbles you burst at the same time, the more points you earn. With 3 different game modes you will have a hard time putting this game down - excellent for small breaks.
  :developer: 
    :name: Z Games Studios
    :link: http://www.z-games-studios.com/
  :platform: 
    :name: Windows Phone
    :link: http://www.microsoft.com/windowsphone//s?appid=776114ed-4bda-df11-a844-00237de2db9e
- :name: Pandemic Evolved
  :image: pandemicevolved.png
  :description: The cute viruses are back! The world needs you to save it from the Pandemic... again. Pandemic Evolved is Tetris meets Flowers. Pieces containing 3 viruses keep dropping and you have to match 4 or more of the same color to destroy them. Use bombs and rainbow viruses to help you in your mission. In-game awards for performing special tasks.
  :developer: 
    :name: Z Games Studios
    :link: http://www.z-games-studios.com/
  :platform: 
    :name: Windows Phone
    :link: http://windowsphone.com/s?appid=d99beef9-3060-e011-81d2-78e7d1fa76f8
- :name: Pandemic
  :image: pandemic.png
  :description: Swarms of cute little viruses are invading your world and your objective is to stop them. Pandemic is a puzzle game where you try to achieve a high score by matching 3 or more viruses in a vertical, horizontal or diagonal line and creating combos to multiply your score. The game has 2 different game modes.
  :developer: 
    :name: Z Games Studios
    :link: http://www.z-games-studios.com/
  :platform: 
    :name: Windows Phone
    :link: http://www.microsoft.com/windowsphone//s?appid=4edb73a1-153f-e011-854c-00237de2db9e
- :name: Slice and Throw
  :image: sliceandthrow.png
  :description: Swipe your finger to slice things in half, tap the screen to throw ninja stars. It's that easy and a ton of fun. Can you top the leaderboards? Can you get to level 10? You must slice all the way through things for it to count. Good luck.
  :developer: 
    :name: Cheese Zombie Games
    :link: http://cheesezombiegames.com/
  :platform: 
    :name: Windows Phone
    :link: http://social.zune.net/redirect?type=phoneApp&id=12fc74f5-c864-e011-81d2-78e7d1fa76f8
- :name: Word Tangle
  :image: wordtangle.gif
  :description: If you like addictive word games like Boggle then you will love Word Tangle. Simply make words from the letters in the game board to score points. Some letters add extra time and some add extra points. Everyone in the family can play and each players progress is tracked.
  :developer: 
    :name: Cheese Zombie Games
    :link: http://cheesezombiegames.com/
  :platform: 
    :name: Windows Phone
    :link: http://social.zune.net/redirect?type=phoneApp&id=6f5faaa0-d705-e011-9264-00237de2db9e
- :name: Triad
  :image: triad.png
  :description: "A visual puzzle game that has challenged and fascinated players for nearly a decade! Triad is a tile-matching game with a twist: the tiles you match are never identical, but instead must form any of 256 different patterns.  As you stretch your mind's eye, you'll find you're able to discern Triads faster and faster."
  :developer: 
    :name: Random Software
    :link: http://randomsoftware.com/triad
  :platform: 
    :name: Windows Phone
    :link: http://social.zune.net/redirect?type=phoneApp&id=cebf3480-5240-4b4d-8446-2a7e34dc8619 
- :name: Square Off
  :image: squareoff.png
  :description: "Blast, dodge and disintegrate your alien enemies in a desperate bid to save humanity. Wield shotguns, bombs and missiles in an insane survival frenzy. Features beautiful sound and 2.5D graphics, hordes of vicious aliens and absolutely loads of addictive fun."
  :developer: 
    :name: Gnomic Studios
    :link: http://www.gnomicstudios.com/
  :platform: 
    :name: Windows Phone
    :link: http://www.windowsphone.com/en-US/apps/6a8eef97-9b36-4caa-8d4b-bea5732406de
- :name: Danger Winger
  :image: dangerwinger.png
  :description: "You are the Danger Wing. You've been assigned to investigate the recent rise in Space Pirate activity. Space Pirates have always been a minor threat in the area, but recently they have become more brazen. Who is responsible for uniting them? Why don't they just get real jobs like the rest of us?"
  :developer: 
    :name: Paul Hoenecke
    :link: http://www.wp7connect.com/2011/06/02/game-review-danger-wing/
  :platform: 
    :name: Windows Phone
    :link: http://www.windowsphone.com/en-US/apps/e98d8bea-cf88-e011-986b-78e7d1fa76f8
- :name: Get Cho' Chicken
  :image: getchochicken.png
  :description: "Come on down to the country with this fun filled game for the whole family and all ages! YEEEE HAAA!! Farmer Bill's Chickens has escaped the coop! Help him get back as many as he can before time runs out! But look out the chickens aren't going back without a fight! Try to get as many targets as possible before time expires!"
  :developer: 
    :name: T-Ray Studios
    :link: http://www.windowsphone.com/en-US/publishers/T-Ray%20Studios?appid=f6d416d7-ae2b-4532-bfcb-b572f01ad67e&name=T-Ray%20Studios
  :platform: 
    :name: Windows Phone
    :link: http://windowsphone.com/s?appid=c09d2ec7-ca8c-407f-9a32-1aad3ca36dea
- :name: Unscramble 
  :image: unscramble.png
  :description: "Test your knowledge of English by unscrambling words within 45 seconds. Each time you correctly unscramble a word, you are presented with a new word that is just a little bit more difficult. The more you play, the more difficult the game gets. Look to word meanings for hints."
  :developer: 
    :name: RJ Software
    :link: http://www.windowsphone.com/en-US/publishers/RJ%20Software?appid=057e1444-e745-4557-8ea3-20e03b065125&name=RJ%20Software
  :platform: 
    :name: Windows Phone
    :link: http://www.windowsphone.com/en-US/apps/057e1444-e745-4557-8ea3-20e03b065125
- :name: Galaxy Jet
  :image: galaxyjet.png
  :description: "Survive the waves of asteroids in this ultimate side-scrolling space shooter game. Shoot-em-up all and beware of the yellow planets. Use the lasers and shock waves to get extra bonus points! Compare your score in the online leaderboards. This unique game was specifically designed for the Windows Phones, it's free and without ads!"
  :developer: 
    :name: Tomas Slavicek
    :link: http://www.windowsphone.com/en-US/apps/ba54f5cb-09c5-4949-b703-2db370abfcc7
  :platform: 
    :name: Windows Phone
    :link: http://www.windowsphone.com/en-US/apps/ba54f5cb-09c5-4949-b703-2db370abfcc7
- :name: Linerous
  :image: linerous.png
  :description: "Linerous je jednoduchá logická hra postavená na notně přepracovaném principu hledání min. Najdete zde jak normální herní mód, kde si hru nastavíte přesně podle libosti, tak i závod s časem, s jehož výsledkem se následně budete moci pochlubit v online žebříčcích. Nechybí zde ale ani achievementy."
  :developer: 
    :name: Petr Houška
    :link: "http://twitter.com/#!/petrroll"
  :platform: 
    :name: Windows Phone
    :link: http://www.windowsphone.com/cs-CZ/apps/4fa849bb-6a20-4c8a-b6ed-0b51a94f4ac5
- :name: aPuzzleIntrusion
  :image: aPuzzleIntrusion.png
  :description: "Another classic puzzle game? WRONG! aPuzzleIntrusion is not another classic puzzle game, you must solve 20 puzzles for each month avoiding to hit and smash the various cockroaches intruders, otherwise they'll squeeze out the puzzle! Each puzzle solved will bring you to the next level, for each level will increase the cockroaches number!"
  :developer: 
    :name: Carucci Fabio
    :link: "http://blogs.ugidotnet.org/FabioCarucci/Default.aspx"
  :platform: 
    :name: Windows Phone
    :link: http://www.windowsphone.com/en-US/apps/0ae15251-8f9a-413d-b5dc-3df1288e4834
- :name: Protect Our Nuke
  :image: protectournuke.png
  :description: "They desperately seek our nuclear weapons and are coming hard at us with all they have. The time has come to deploy our best and ward off the waves to protect our precious resources. The battle is on! "
  :developer: 
    :name: CandelaCreations 
    :link: "http://www.windowsphone.com/en-US/publishers/CandelaCreations?appid=cbc87853-6301-4c43-aa95-c2293b1aa37b&name=CandelaCreations"
  :platform: 
    :name: Windows Phone
    :link: http://www.windowsphone.com/en-US/apps/cbc87853-6301-4c43-aa95-c2293b1aa37b
- :name: Rain Will Fall
  :image: rainwillfall.png
  :description: "Your planet is being taken over by an alien race. Beat the game and unlock the mysteries! Find out why this is happening! When you think you have mastered the controls! Bring your skill online. Challenge anyone at anytime(Must Have Wifi Connection) Have 1 on 1's with anyone!. Show everyone what you got."
  :developer: 
    :name: L0RD-0DIN 
    :link: "http://www.l0rd0dingames.com/"
  :platform: 
    :name: Windows Phone
    :link: http://www.windowsphone.com/en-us/apps/04b9c82d-68f2-4b8f-b05c-acd3be7c0bdf
- :name: BuzzWords
  :image: buzzwords.png
  :description: "Buzzwords is a fast paced arcade style word game. Find words in any direction for points. The more words you chain together, the larger your score. Beware of those pesky bugs, and don’t let them fall in your honey pot!  Full version includes two game modes and the option to select boosters for an enhanced experience!"
  :developer: 
    :name: M80 Games
    :link: http://www.m80games.com/
  :platform: 
    :name: Windows Phone
    :link: http://www.windowsphone.com/en-US/apps/c98c9011-84ce-4c78-831b-13a278dc26a7