development:
  mongo:
    host: localhost
    port: 27017
    name: mogade2_dev
    
test:
  mongo:
    host: localhost
    port: 27017
    name: mogade2
    
production:
  mongo:
    host: localhost
    port: 27017
    name: mogade2