development:
  cdn_url: http://0.0.0.0:3000
  ssl_cdn_url: http://0.0.0.0:3000
  postmark_key: postmark_api_key
  mongo:
    host: localhost
    port: 27017
    name: mogade2_dev
  redis:
    host: localhost
    port: 6379
    database: 0
    
test:
  cdn_url: http://0.0.0.0:3000
  ssl_cdn_url: http://0.0.0.0:3000
  postmark_key: postmark_api_key
  mongo:
    host: localhost
    port: 27017
    name: mogade2
  redis:
    host: localhost
    port: 6379
    database: 1
    
production:
  cdn_url: http://0.0.0.0:3000
  ssl_cdn_url: http://0.0.0.0:3000
  #hoptoad_key: optional_hoptoad_key
  postmark_key: postmark_api_key
  mongo:
    host: localhost
    port: 27017
    name: mogade2
  redis:
    host: localhost
    port: 6379
    database: 0